start the changes required to support python 3.11, ustreamer and sftp pellcorp k1_buildroot packages

diff --git a/k1/services/S50webcam b/k1/services/S50webcam
--- a/k1/services/S50webcam
+++ b/k1/services/S50webcam
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+PID_FILE=/run/ustreamer.pid
+
 case "$1" in
   start)
     V4L_DEVICE=$(v4l2-ctl --list-devices|grep -A1 usb|sed 's/^[[:space:]]*//g'|grep '^/dev' | head -1)
@@ -8,10 +10,11 @@ case "$1" in
       exit 1
     fi
 
-    /opt/bin/mjpg_streamer -b -i "/opt/lib/mjpg-streamer/input_uvc.so -d $V4L_DEVICE -r 1280x720 -f 15" -o "/opt/lib/mjpg-streamer/output_http.so -p 8080"
+    LD_LIBRARY_PATH=/opt/lib:/opt/usr/lib start-stop-daemon -S -b -m -p $PID_FILE --exec "/opt/usr/bin/ustreamer" -- -d $V4L_DEVICE -r 1280x720 -m MJPEG --device-timeout=2 -w 1 -I MMAP -c HW -p 8080 -s*
     ;;
   stop)
-    killall mjpg_streamer
+    start-stop-daemon -K -p $PID_FILE
+   [ $? = 0 ] && echo "OK" || echo "FAIL"
     ;;
 
   restart|reload)
